Repository Dani-gr/MIAU, pull requests merged in 2023-05, with the labels that each got.

#23 Audios in study mode
  ClientApp/js/animalStudy.js
  ClientApp/js/colorStudy.js
  ClientApp/js/numberStudy.js
  ClientApp/mainmenu.html
  ClientApp/resources/iconodealtavozsorry.jpg
  ClientApp/resources/sounds/amarillo yellow.aac
  ClientApp/resources/sounds/aqua aqua.aac
  ClientApp/resources/sounds/azul blue.aac
  ClientApp/resources/sounds/blanco white.aac
  ClientApp/resources/sounds/cinco five.aac
  ClientApp/resources/sounds/cuatro four.aac
  ClientApp/resources/sounds/diez ten.aac
  ClientApp/resources/sounds/dos two.aac
  ClientApp/resources/sounds/elefante elephant .aac
  ClientApp/resources/sounds/gris gray.aac
  ClientApp/resources/sounds/león lion.aac
  ClientApp/resources/sounds/morado purple.aac
  ClientApp/resources/sounds/naranja orange.aac
  ClientApp/resources/sounds/negro black.aac
  ClientApp/resources/sounds/oveja sheep.aac
  ClientApp/resources/sounds/perro dog.aac
  ClientApp/resources/sounds/rojo red.aac
  ClientApp/resources/sounds/seis six.aac
  ClientApp/resources/sounds/tiburón shark.aac
  ClientApp/resources/sounds/tres three.aac
  ClientApp/resources/sounds/uno one.aac
  ClientApp/resources/sounds/verde green.aac
  ClientApp/studyanimals.html
  ClientApp/studycolors.html
  ClientApp/studynumbers.html
  ClientApp/styles/studyActivities/studyAnimals.css
  ClientApp/styles/studyActivities/studyColors.css
  ClientApp/styles/studyActivities/studyNumbers.css
  ClientApp/styles/studyStyle.css
Labels: accesibility

#24 Carlos
  ClientApp/index.html
  ClientApp/login.html
  ClientApp/resources/play-button.png
  ClientApp/styles/indexStyle.css
  ClientApp/styles/loginStyle.css
Labels: accesibility, responsiveness

#20 made main menu responsive
  ClientApp/mainmenu.html
  ClientApp/styles/mainMenu.css
Labels: responsiveness
